apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - taskRef:
        name: the-task
      name: xx1
    - taskSpec:
        steps:
          - name: echo
            image: ubuntu
            command:
              - echo
            args:
              - "02 taskspec"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: the-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "02 version"

